name = "Technology in the Sea"
author = "skippyall"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa36b33ffb0c422940c89f75d2ebd4f6fd0fe8fda311b5d3f7dc60d33d7ad271"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
