name = "Technology in the Sea"
author = "skippyall"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4092538a82c8e29b347e094cb406f11a66f8ced89dc448eff80cd085d412d94"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
