name = "Technology in the Sea"
author = "skippyall"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e60ab7f1fb4c8fbb53ba0931f3c9f255962ee9df2265872d8b4645c0a2a8460"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
