name = "Technology in the Sea"
author = "skippyall"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7faec32d13693bf09d46080e495d38116086f736bed450916fbcd09fbe1edde"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
