name = "Technology in the Sea"
author = "skippyall"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "674959a9cf26e54bfcc2a1dbe8984ec9cff1f9bdb75cf0e2ed90c9abb9459650"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
