name = "Technology in the Sea"
author = "skippyall"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feb49a99248db327f812525a83fc825f37f7b80f2c5cb25f9a1359d32f730dce"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
