name = "Technology in the Sea"
author = "skippyall"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c068e84dc8d51f0db1e2a108c2b8a8083be8e2995b3bac9767a76e45f9742d32"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
