name = "Technology in the Sea"
author = "skippyall"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98fcd753801a523f27d404361b4f7a2e71c81380518f5670d642f9c44c4b2187"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
